## Deliverable 2. Create a Customer Travel Destinations Map.

In [22]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [23]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
0,0,Bluff,-46.6000,168.3333,64.80,66,100,7.36,2022-02-14 04:50:26
1,1,Georgetown,5.4112,100.3354,87.73,74,20,5.75,2022-02-14 04:47:55
2,2,Sikeston,36.8767,-89.5879,30.09,64,0,5.73,2022-02-14 04:50:26
3,3,Iroquois Falls,48.7669,-80.6831,-23.66,99,44,3.24,2022-02-14 04:50:27
4,4,Upernavik,72.7868,-56.1549,1.58,92,100,17.60,2022-02-14 04:50:27

In [24]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 95

In [25]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
vacation_cities = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) & (city_data_df["Max Temp"] <= max_temp)]
vacation_cities.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
1,1,Georgetown,5.4112,100.3354,87.73,74,20,5.75,2022-02-14 04:47:55
6,6,Busselton,-33.6500,115.3333,92.05,40,0,0.83,2022-02-14 04:50:28
7,7,Stanger,-29.3282,31.2895,76.91,87,94,12.73,2022-02-14 04:50:28
8,8,Benalla,-36.5500,145.9833,94.98,21,1,7.05,2022-02-14 04:50:28
9,9,Rikitea,-23.1203,-134.9692,78.91,71,1,14.12,2022-02-14 04:50:29

In [26]:
# 4a. Determine if there are any empty rows.
vacation_cities.isnull().sum()
print("There are 0 empty rows")

There are 0 empty rows

In [27]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = vacation_cities.copy()

In [30]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Max Temp", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City  Max Temp      Lat       Lng Hotel Name
1   Georgetown     87.73   5.4112  100.3354
6    Busselton     92.05 -33.6500  115.3333
7      Stanger     76.91 -29.3282   31.2895
8      Benalla     94.98 -36.5500  145.9833
9      Rikitea     78.91 -23.1203 -134.9692
10     Ternate     83.03   0.8000  127.4000
13       Kapaa     75.18  22.0752 -159.3190
22   Wattegama     81.52   6.7989   81.4808
24      Atuona     77.34  -9.8000 -139.0333
26    Bengkulu     84.96  -3.8004  102.2655

In [40]:
for index, row in hotel_df.iterrows():
    lat = row['Lat']

In [44]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["lat"]
    
#     # 6d. Set up the base URL for the Google Directions API to get JSON data.
#     base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

#     # 6e. Make request and retrieve the JSON data from the search. 
#     hotels = requests.get(base_url, params=params).json()
   
    
#     # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    
#     # Set the parameters to search for a hotel in Paris.
    
#     # Iterate through the DataFrame.
# for index, row in hotel_df.iterrows():
#     # Get the latitude and longitude.
#     lat = row["Lat"]
#     lng = row["Lng"]

#     # Add the latitude and longitude to location key for the params dictionary.
#     params["location"] = f"{lat},{lng}"

#     # Use the search term: "lodging" and our latitude and longitude.
#     base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
#     # Make request and get the JSON data from the search.
    
#     hotels = requests.get(base_url, params=params).json()
    
#     # Grab the first hotel from the results and store the name.
#     try:
#         hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
#     except (IndexError, KeyError):
#         print("Hotel not found... skipping.")

KeyError: 'lat'

In [ ]:
# 7. Drop the rows where there is no Hotel Name.

In [ ]:
# 8a. Create the output File (CSV)

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [ ]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure